name: build-release-test

on: [push]

jobs:
    build-ubuntu:
        name: Build Ubuntu and Test
        runs-on: ubuntu-latest
        container:
            image: ubuntu:18.04
            env:
                TZ: America/New_York
                DEBIAN_FRONTEND: noninteractive
        services:
            mysql:
                image: mysql:latest
                env:
                    MYSQL_ROOT_PASSWORD: rootpw
                    MYSQL_DATABASE: test_db
                    MYSQL_USER: user
                    MYSQL_PASSWORD: passw0rd
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: apt
                run: |
                    apt-get update
                    apt-get -y upgrade
                    apt install -y build-essential software-properties-common
                    add-apt-repository ppa:ubuntu-toolchain-r/test
                    apt-get -y install \
                        git \
                        cmake \
                        ninja-build \
                        g++-9 \
                        clang-9 \
                        zlib1g-dev \
                        libuv1-dev \
                        libssl-dev \
                        libmysqlclient-dev \
                        netcat
            -   name: build-release-g++
                run: |
                    mkdir build-release-g++
                    cd build-release-g++
                    cmake \
                        -GNinja \
                        -DWING_MYSQL_CLIENT_LIB:STRING=libmysqlclient.so \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=gcc-9 \
                        -DCMAKE_CXX_COMPILER=g++-9 \
                        ..
                    ninja
            -   name: build-release-clang
                run: |
                    mkdir build-release-clang
                    cd build-release-clang
                    cmake \
                        -GNinja \
                        -DWING_MYSQL_CLIENT_LIB:STRING=libmysqlclient.so \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=clang-9 \
                        -DCMAKE_CXX_COMPILER=clang++-9 \
                        ..
                    ninja
            -   name: wait for mysql to start
                run: |
                    for i in `seq 1 30`;
                    do
                        nc -z mysql 3306 && echo "Connected to MySQL." && exit 0
                        echo -n
                        sleep 1
                    done
                    echo Failed waiting for MySQL && exit 1
            -   name: test-release-g++
                run: |
                    ./build-release-g++/test/libwingmysql_tests
                    # Can be run with ctest but directly running gives better errors.
                    # cd build-release-g++
                    # ctest -v
            -   name: test-release-clang
                run: |
                    ./build-release-clang/test/libwingmysql_tests
                    # Can be run with ctest but directly running gives better errors.
                    # cd build-release-clang
                    # ctest -v
    build-fedora:
        name: Build Fedora and Test
        runs-on: ubuntu-latest
        container:
            image: fedora:31
        services:
            mysql:
                image: mysql:latest
                env:
                    MYSQL_ROOT_PASSWORD: rootpw
                    MYSQL_DATABASE: test_db
                    MYSQL_USER: user
                    MYSQL_PASSWORD: passw0rd
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: dnf
                run: |
                    sudo dnf install -y \
                        git \
                        cmake \
                        ninja-build \
                        g++ \
                        clang \
                        zlib-devel \
                        libuv-devel \
                        openssl-devel \
                        mysql-devel \
                        nc
            -   name: build-release-g++
                run: |
                    mkdir build-release-g++
                    cd build-release-g++
                    cmake \
                        -GNinja \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=gcc \
                        -DCMAKE_CXX_COMPILER=g++ \
                        ..
                    ninja
            -   name: build-release-clang
                run: |
                    mkdir build-release-clang
                    cd build-release-clang
                    cmake \
                        -GNinja \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=clang \
                        -DCMAKE_CXX_COMPILER=clang++ \
                        ..
                    ninja
            -   name: wait for mysql to start
                run: |
                    for i in `seq 1 30`;
                    do
                        nc -z mysql 3306 && echo "Connected to MySQL." && exit 0
                        echo -n
                        sleep 1
                    done
                    echo Failed waiting for MySQL && exit 1
            -   name: test-release-g++
                run: |
                    ./build-release-g++/test/libwingmysql_tests
                    # Can be run with ctest but directly running gives better errors.
                    # cd build-release-g++
                    # ctest -v
            -   name: test-release-clang
                run: |
                    ./build-release-clang/test/libwingmysql_tests
                    # Can be run with ctest but directly running gives better errors.
                    # cd build-release-clang
                    # ctest -v
