name: build-release-test

on: [push]

jobs:
    build-ubuntu-18-04:
        name: ubuntu.18.04
        runs-on: ubuntu-latest
        container:
            image: ubuntu:18.04
            env:
                TZ: America/New_York
                DEBIAN_FRONTEND: noninteractive
        services:
            mysql:
                image: mysql:latest
                env:
                    MYSQL_ROOT_PASSWORD: rootpw
                    MYSQL_DATABASE: wing_db
                    MYSQL_USER: user
                    MYSQL_PASSWORD: passw0rd
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: apt
                run: |
                    apt-get update
                    apt-get -y upgrade
                    apt install -y build-essential software-properties-common
                    add-apt-repository ppa:ubuntu-toolchain-r/test
                    apt-get -y install \
                        git \
                        cmake \
                        ninja-build \
                        g++-9 \
                        clang-9 \
                        zlib1g-dev \
                        libssl-dev \
                        libmysqlclient-dev \
                        netcat
            -   name: build-release-g++
                run: |
                    mkdir build-release-g++
                    cd build-release-g++
                    cmake \
                        -GNinja \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=gcc-9 \
                        -DCMAKE_CXX_COMPILER=g++-9 \
                        ..
                    ninja
            -   name: build-release-clang
                run: |
                    mkdir build-release-clang
                    cd build-release-clang
                    cmake \
                        -GNinja \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=clang-9 \
                        -DCMAKE_CXX_COMPILER=clang++-9 \
                        ..
                    ninja
            -   name: wait for mysql to start
                run: |
                    for i in `seq 1 30`;
                    do
                        nc -z mysql 3306 && echo "Connected to MySQL." && exit 0
                        echo -n
                        sleep 1
                    done
                    echo Failed waiting for MySQL && exit 1
            -   name: test-release-g++
                run: |
                    cd build-release-g++
                    ctest -v
            -   name: test-release-clang
                run: |
                    cd build-release-clang
                    ctest -v
    build-ubuntu-20-04:
        name: ubuntu-20.04
        runs-on: ubuntu-latest
        container:
            image: ubuntu:20.04
            env:
                TZ: America/New_York
                DEBIAN_FRONTEND: noninteractive
        services:
            mysql:
                image: mysql:latest
                env:
                    MYSQL_ROOT_PASSWORD: rootpw
                    MYSQL_DATABASE: wing_db
                    MYSQL_USER: user
                    MYSQL_PASSWORD: passw0rd
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: apt
                run: |
                    apt-get update
                    apt-get -y upgrade
                    apt install -y build-essential software-properties-common
                    add-apt-repository ppa:ubuntu-toolchain-r/test
                    apt-get -y install \
                        git \
                        cmake \
                        ninja-build \
                        g++-9 \
                        clang-9 \
                        zlib1g-dev \
                        libssl-dev \
                        libmysqlclient-dev \
                        netcat
            -   name: build-release-g++
                run: |
                    mkdir build-release-g++
                    cd build-release-g++
                    cmake \
                        -GNinja \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=gcc-9 \
                        -DCMAKE_CXX_COMPILER=g++-9 \
                        ..
                    ninja
            -   name: build-release-clang
                run: |
                    mkdir build-release-clang
                    cd build-release-clang
                    cmake \
                        -GNinja \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=clang-9 \
                        -DCMAKE_CXX_COMPILER=clang++-9 \
                        ..
                    ninja
            -   name: wait for mysql to start
                run: |
                    for i in `seq 1 30`;
                    do
                        nc -z mysql 3306 && echo "Connected to MySQL." && exit 0
                        echo -n
                        sleep 1
                    done
                    echo Failed waiting for MySQL && exit 1
            -   name: test-release-g++
                run: |
                    cd build-release-g++
                    ctest -v
            -   name: test-release-clang
                run: |
                    cd build-release-clang
                    ctest -v
    build-fedora-31:
        name: fedora-31
        runs-on: ubuntu-latest
        container:
            image: fedora:31
        services:
            mysql:
                image: mysql:latest
                env:
                    MYSQL_ROOT_PASSWORD: rootpw
                    MYSQL_DATABASE: wing_db
                    MYSQL_USER: user
                    MYSQL_PASSWORD: passw0rd
        steps:
            -   name: Checkout
                uses: actions/checkout@v2
            -   name: dnf
                run: |
                    sudo dnf install -y \
                        git \
                        cmake \
                        ninja-build \
                        gcc-c++-9.3.1 \
                        clang-9.0.1 \
                        lcov \
                        zlib-devel \
                        openssl-devel \
                        mysql-devel \
                        nc
            -   name: build-debug-g++
                run: |
                    mkdir build-debug-g++
                    cd build-debug-g++
                    cmake \
                        -GNinja \
                        -DWING_CODE_COVERAGE=ON \
                        -DCMAKE_BUILD_TYPE=Debug \
                        -DCMAKE_C_COMPILER=gcc \
                        -DCMAKE_CXX_COMPILER=g++ \
                        ..
                    ninja
            -   name: build-release-g++
                run: |
                    mkdir build-release-g++
                    cd build-release-g++
                    cmake \
                        -GNinja \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=gcc \
                        -DCMAKE_CXX_COMPILER=g++ \
                        ..
                    ninja
            -   name: build-release-clang
                run: |
                    mkdir build-release-clang
                    cd build-release-clang
                    cmake \
                        -GNinja \
                        -DCMAKE_BUILD_TYPE=Release \
                        -DCMAKE_C_COMPILER=clang \
                        -DCMAKE_CXX_COMPILER=clang++ \
                        ..
                    ninja
            -   name: wait for mysql to start
                run: |
                    for i in `seq 1 30`;
                    do
                        nc -z mysql 3306 && echo "Connected to MySQL." && exit 0
                        echo -n
                        sleep 1
                    done
                    echo Failed waiting for MySQL && exit 1
            -   name: test-release-g++
                run: |
                    cd build-release-g++
                    ctest -v
            -   name: test-release-clang
                run: |
                    cd build-release-clang
                    ctest -v
            -   name: Build coverage info
                run: |
                    cd build-debug-g++
                    ctest -v
                    gcov -o ./test/CMakeFiles/libwingmysql_tests.dir/main.cpp.p ./test/libwingmysql_tests
                    lcov --include "*/inc/wing/*" --include "*/src/*" --exclude "test/*" -o libwingmysql_tests.info -c -d .
            -   name: Coveralls GitHub Action
                uses: coverallsapp/github-action@v1.0.1
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    path-to-lcov: build-debug-g++/libwingmysql_tests.info
